### ISSUE TITLE
Select2 is allowing tags bigger than maximumInputLength via copy paste.

### ISSUE THREAD

**Issue by migueljbento** [select2/select2#1491]
I have a select2 in tag mode that allows the user to create new tags. Although i specify a maximumInputLength there are some situations where we can create tags bigger than it.

If i start typing and exceed 20 chars, a message saying "Please delete X character" appears. This is the expected behavior. However, if you create a really big string and paste it into the select2 and press tab right away it ignores the limit and creates the tag. This isn't always reproducible but happens more if you have one tag already defined.

Here's my select2 configuration:
{
                minimumResultsForSearch: 5,
                multiple: true
                tokenSeparators: [",", " "],
                placeholder: 'Select list tags',
                maximumInputLength: 20,
                createSearchChoice: function (term, data) {
                   if (_.every(data, function (currTag) {
                        /** We need to verify if the new tag matches any of the existing tags to prevent its creation. */
                        return currTag.text.localeCompare(term) !== 0;
                    })) {
                        return {id: term, text: term};
                    }
                },
                ajax: {
                    results: function (result) {
                        return {
                            results: _.map(result.items, function (element) {
                                return {
                                    id: element.id,
                                    text: element.name
                                };
                            }),
                            more: result.offset + 5 < result.collectionSize
                        };
                    }
                },
                formatNoMatches: _.constant('No Matches')
}

**Comment by kevin-brown** [comment]
This issue should have been fixed in later versions of Select2.

**Comment by jim-at-miramontes** [comment]
I'm still seeing this regularly in 4.0.5.  If I hit TAB at the end of the string, the item disappears (Intended behavior?).  But if I enter a comma, as if I was going to add another item, the overly-long item is created and added to the field, with all its excessive characters.  It doesn't seem to matter if the string is pasted in or created through regular text entry.
