### ISSUE TITLE
Problem with declaring callbacks in the data-* attributes

### ISSUE THREAD

**Issue by akozhemiakin** [select2/select2#2957]
What I like about select2 is the idea to specify all configuration parameters in data-\* attributes.

Suppose I have some sort of templating function stored in my namespace:

``` javascript
window.myNamespace = {
    templateResult: function(item) {
        if (item.loading) return item.text;
        return '<div>' + item.text + ' (' + item.price + ')' + '</div>';
    }
}
```

Now I want to specify this function as a callback in my select tag in data-template-result attribute like that:

``` html
<select class="select2" data-template-result="myNamespace.templateResult"></select>
```

Clean and cool but does not work. The reason is, as we can read from the Jquery docs: "Every attempt is made to convert the string to a JavaScript value (this includes booleans, numbers, objects, arrays, and null)". No function in this list. So, now there is no legal way to declare callbacks using data-\* attributes.

For now I'm using the following workaround: 
I'm prefixing all my callback names with '_fn::' like this: "_fn::myNamespace.templateResult". Then, before activating any select tag with select2(), I'm using the following function to let jQuery know about callbacks declared in data-\* attributes:

``` javascript
function(obj) {
    var getFunctionByName = function (functionName, context) {
        context = typeof context === 'undefined' ? window : context;
        var namespaces = functionName.split(".");
        var func = namespaces.pop();
        for(var i = 0; i < namespaces.length; i++) {
            context = context[namespaces[i]];
        }
        return context[func];
    }
    var $obj = $(obj);
    $.each($obj.data(), function(key, el) {
        if (typeof el === 'string' && el.substr(0, 5) == '_fn::') {
            $obj.data(key, getFunctionByName(el.substr(5)));
        }
    });
}
```

Works just fine, but looks like a hack.

Maybe we can do something with select2 behavior itself to let users legally specify callbacks in data attributes without using such external hacks?

**Comment by donaldinou** [comment]
agreed :+1:

**Comment by meridius** [comment]
I'd also like to see this implemented. Until then here are my two cents to this since I had a hard time to copy-paste use the solution @numesmat posted, so I tweaked it a bit.

```html
<select data-template-selection="_fn::userManagementComponent.formatUserName">
...
</select>
```

```javascript
// somewhere close to the <select> in question since the 
// templating function is supposed to be coined for specific use just with that one element
window.movieDb.userManagementComponent = {};
window.movieDb.userManagementComponent.formatUserName = function(item) {
	return (item.text === "") 
		 ? $("<b>no login yet</b>")
		 : item.text;
};
```

```javascript
// some main.js file or something
$.fn.initSelect2DataFunctions = function(context) {
	
	var functionPrefix = '_fn::';
	
	var getFunctionByName = function(functionName, context) {
		context = typeof context === 'undefined' ? window : context;
		var namespaces = functionName.split(".");
		var func = namespaces.pop();
		for (var i = 0; i < namespaces.length; i++) {
			context = context[namespaces[i]];
		}
		return context[func];
	};
	
	return this.each(function() {
		var el = $(this);
		$.each(el.data(), function(key, val) {
			if (typeof val === 'string' && val.substr(0, 5) === functionPrefix) {
				el.data(key, getFunctionByName(val.substr(5), context));
			}
		});
	});
	
};

$(".select2").initSelect2DataFunctions(window.movieDb).select2();
```

**Comment by th3byrdm4n** [comment]
Here's a rushed newbie impl. from feedback... not going to fix it for source patch until I have time to do it right; https://github.com/select2/select2/commit/5142d314ac926372f5e8d9cc4dbd49a4082ccf33

**Comment by md5** [comment]
See #4715 for a proposed implementation of this functionality.

**Comment by alexweissman** [comment]
Another option would be to use `eval`, as per [this post](https://stackoverflow.com/questions/30028331/pass-javascript-function-as-data-attribute-and-execute), although that presents its own problems.

**Comment by knightq** [comment]
Seems like a duplication of issue #4715 fixed by @vladkucherov with with the open [PR#4715](https://github.com/select2/select2/pull/4715/commits/218dd7e70620a14002beefdf23f9a1b7caf278b2), isn't it?

**Comment by dwasyl** [comment]
This is still an issue and a simple fix like one of the suggestions would be fantastic in the next release. Is it possible to revisit, there are existing PRs (closed) that would address the issue.
