### ISSUE TITLE
select2 4.0 - dropdownAutoWidth not working

### ISSUE THREAD

**Issue by santaclaus21** [select2/select2#3101]
option dropdownAutoWidth is not working in 4.0. It's important in my case...

**Comment by kevin-brown** [comment]
Merging into https://github.com/select2/select2/issues/3101.

**Comment by kvikram1988** [comment]
Is this fix available as part of 4.0.0 release. When will we get it into any further release???

**Comment by kevin-brown** [comment]
Unfortunately that other ticket was closed off as being a different issue, so I'm reopening this one temporarily.
`dropdownAutoWidth` was added back in time for 4.0.0 (this commit: https://github.com/select2/select2/commit/e416e47356b2a92792e2c083a3d5ee9bdba5f908).

----

Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by santaclaus21** [comment]
This is still not working in 4.0.1.

{width: 'resolve', theme: 'classic', dropdownAutoWidth: 'true'}
![image](https://cloud.githubusercontent.com/assets/1121662/11146121/af98185a-8a0b-11e5-89e9-ad79734671b2.png)

in 3.5.2 looks good:
![image](https://cloud.githubusercontent.com/assets/1121662/11146156/e9425dd6-8a0b-11e5-88d0-074893ff68a4.png)

**Comment by G4g4Rm3L** [comment]
I have the same problem. It works for me if I add "css.position = 'relative';" at line 4246 (select2.full.js / 4.0.1)

```javascript
    if (this.options.get('dropdownAutoWidth')) {
      css.minWidth = css.width;
      css.width = 'auto';
      css.position = 'relative';
    }
```

**Comment by santaclaus21** [comment]
As @G4g4Rm3L said, should be added "css.position = 'relative';" at if (this.options.get('dropdownAutoWidth')). Without this change option not working for me.

**Comment by joetidee** [comment]
Please re-open. Still has issues with not auto-sizing to the container of the select2:

https://jsfiddle.net/fbz0mngp/4/

**Comment by santaclaus21** [comment]
Hm... https://jsfiddle.net/fbz0mngp/7/. It looks fine for me (?)

**Comment by joetidee** [comment]
In this example, would you not expect the select to act responsively and shrink down to fill the right-most div ?:

https://jsfiddle.net/fbz0mngp/17/
