### ISSUE TITLE
Hitting backspace on multi-select converts element to text

### ISSUE THREAD

**Issue by pjclas** [select2/select2#3354]
Perhaps this is intended behavior but it seems odd to me.  If you use the backspace key to delete an element in a multi-select box, that element doesn't go away like it would if you clicked the 'x'.  Instead it is converted to text with an additional space at the end that you have to backspace through to get rid of.  Is this intended?  Would be nice to have an option to disable it if that is the case.  Fiddle providede below:

http://jsfiddle.net/y7fo61ms/

**Comment by kevin-brown** [comment]
> Is this intended?

Yup, totally intentional. https://github.com/select2/select2/commit/395e06aff52059f654aff47f03a26cad8955a092

> Would be nice to have an option to disable it if that is the case.

I'm not sure how I feel about having another option for this, I'd like the get the current set documented first. But I can tell you that you can completely erase the search box in [`Search.searchRemoveChoice`](https://github.com/select2/select2/blob/dd9af6893450bbb054ca79546a16bb18198f3e88/src/js/select2/selection/search.js#L127-L135) and it will do what you are looking for.

**Comment by pjclas** [comment]
Hmm, ok.  I guess I'll have to see if I can wrap my head around this
behavior.  Thanks for the info.

**Comment by smajl** [comment]
Wow, I was just surprised by this behavior too. Not what I was used to from 3.5.x. Well, it can be usefull, but there is also a nasty bug, which is already discussed here https://github.com/select2/select2/issues/3297

**Comment by hackeron** [comment]
How to get the old behaviour? - the new behaviour is very undesirable and users are complaining why can they cannot backspace to remove an item and why does it turn into text. Is there any workaround in the meantime?

**Comment by stonexer** [comment]
Can't agree with this behaviour. Just vote to get the old one.

**Comment by kevin-brown** [comment]
Reopening this while we decide how best to handle this.

**Comment by Zane-XY** [comment]
this is really odd,  my tag contains spaces, after I hit backspace, it breaks down to more small tags automatically, and it seems I can never delete all of them.

**Comment by heebj** [comment]
+1

**Comment by ldaguise** [comment]
I also vote for having an option to get back the old behaviour.
Thanks

**Comment by giangt** [comment]
+1
Thanks.

**Comment by gtrman** [comment]
+1

**Comment by rnt363** [comment]
Hey could someone by chance (@kevin-brown) explain if there's a way to override the Search.searchRemoveChoice without forking the repo? I'm trying to avoid this issue: https://github.com/select2/select2/issues/3297 by just removing the whole pill 

Thanks!

**Comment by zyphlar** [comment]
:+1: I can't decide if Chosen is better despite not being able to keep the multi-select window open after selection, or if Select2 is better despite really buggy backspace behavior.

**Comment by kevin-brown** [comment]
> Hey could someone by chance (@kevin-brown) explain if there's a way to override the Search.searchRemoveChoice without forking the repo?

You can patch this method (not totally recommended by it gets the job done) or create a custom decorator (lacking docs to link to) that overrides this method.

Here's a jsfiddle that demonstrates the patching method

https://jsfiddle.net/zmh90ewu/

**Comment by zyphlar** [comment]
Greatly appreciated, @kevin-brown ! That works, thanks. :heart:

**Comment by giangt** [comment]
Thanks @kevin-brown :+1:

**Comment by SlyDave** [comment]
+1 To have this option, the full clear confused the hell out of our focus group when testing our UI which implements select2 4.0.0, causing multiple bouts of frustration.

Thanks for the patch, that'll suffice for now I guess.

**Comment by Intrepidd** [comment]
This is very weird, in my case when you hit backspace for the first time the value disappears but is not immediately converted to text, you have to press backspace again to convert it to text.

![select2](https://cloud.githubusercontent.com/assets/803765/9877843/a449a416-5bbf-11e5-94c5-f15888cd46d5.gif)

I also have something similar on your example page but only on the second try : 

![select2_2](https://cloud.githubusercontent.com/assets/803765/9877910/24f0e35e-5bc0-11e5-89e2-7f92c4a3b107.gif)

**Comment by SlyDave** [comment]
@Intrepidd, I'd log this as a separate issue. I too experience this. (on FF and Chrome, Windows 7 64bit) on both the examples page for select2 and our own implementations.

(However for me the behaviour was undesired, so I've "resolved" it by changing the backspace behaviour to remove the entire pill, rather than converting it to text)

**Comment by suqi** [comment]
+1

**Comment by corvuscornix** [comment]
+1 and thanks a lot @kevin-brown for the patch!

**Comment by pugnascotia** [comment]
+1, would really like to be able to delete a whole tag on backspace.

**Comment by tuomassalo** [comment]
I believe the use case of not removing the whole tag relies on the idea of

  1. the case when you can add new tags on the fly (which is not enabled behaviour anyway) or

  2. saving some keystrokes when trying (which IMHO does not justify the current behavior: clarity should win over brevity).

Besides, the current behavior is severaly broken. When you press backspace, the tag is removed and *a cropped part* of the tag text is shown. This happens at least on:

Latest Chrome / OSX:
![multi-chrome](https://cloud.githubusercontent.com/assets/189964/10903234/1f72311e-8210-11e5-9761-1f51b4cba301.gif)

Latest Firefox / OSX:
![multi-firefox](https://cloud.githubusercontent.com/assets/189964/10903235/240e07c0-8210-11e5-9652-31063a06b3d5.gif)

IE11 / Win7:
![multi-ie11](https://cloud.githubusercontent.com/assets/189964/10903237/27ef8f62-8210-11e5-9942-180d8c432d5a.gif)

Thus, +1 for eg. the `this.$search.val('');` fix, and maybe a +½ for an option to re-enable the current behavior (sans bugs).

**Comment by arg** [comment]
:+1:. This behavior is really confusing. Would be nice to have an option to turn it off.

**Comment by Sasha4ever** [comment]
+1

**Comment by dpnevmatikos** [comment]
+1

**Comment by sirNemanjapro** [comment]
+1

**Comment by kikimor** [comment]
+1

**Comment by kevin-brown** [comment]
Just going to note that a patch is available for this in https://github.com/select2/select2/issues/3354#issuecomment-132389291.

The problem with the search box being cut off was fixed in 4.0.1.

**Comment by pugnascotia** [comment]
Hmm - last time I tried the patch it didn't work, but this time it did. Whoops. PEBKAC.

**Comment by kikimor** [comment]
@kevin-brown, patch in https://github.com/select2/select2/issues/3354#issuecomment-132389291 does not completely solve the problem when minimumInputLength = 0 and AJAX loading is used.

searchRemoveChoice() calls this.handleSearch() with search query != '' (empty string), so the correct solution (but not perfect, I think) is fully overriden searchRemoveChoice():
```
$.fn.select2.amd.require(['select2/selection/search'], function (Search) {
	Search.prototype.searchRemoveChoice = function (decorated, item) {
		this.trigger('unselect', {
			data: item
		});

		this.$search.val('');
		this.handleSearch();
	};
});
```

**Comment by jmlacroix** [comment]
I have 2 use cases in my app where I use select2: a free-form tag list and a dropdown list with multiple choices. Let's have a look at the backspace behavior from the context of a user.

Tags: As a user, I'm typing a list of tags from the keyboard and select some that are already in the list. I expect to be able to quickly edit them and correct my mistakes with backspace. As a result, the current behavior of editing the selection when hitting backspace works well for tags because they are free-form.

Multiple choices: As a user, I am provided a list of options from which I can select one or many. I do not expect to be able to modify those choices (and if I try, I get a "No results found" message). As a result, the current behavior of allowing a user to edit the selection when hitting backspace is unexpected because it is a search helper.

I would use both behaviors in my app, depending on the context.

Hope this brings a useful point of view.

**Comment by stretch4x4** [comment]
We patched this locally, so I have submitted a pull request.
Currently our items have a code as the ID and a description as the text, the text is just there to help, we  actually only care about the code. The current behaviour was no good to us as backspace would remove our code tag and replace it with a massive description instead of allowing editing of the code directly.

I created the option so that you could specify a string, if it matched a key on the item this is what is returned else if blank then the search will remain empty. Hopefully this helps most people.

@kevin-brown you mentioned documenting the current set of options before adding more, if you point me in the right direction I might be able to make a start on this. I am certainly not aware of all the options but could document as many as I have used / can find if that will help with this issue.

Cheers

**Comment by pleek91** [comment]
Is there documentation for this option. Thanks

**Comment by adopilot** [comment]
sory for spaming 
Does this sill open or can be pached  whit version 4.0.1 ?
I am using it on MVC VS2015 and get Selcet2 via nuget.
I am facing this problem

**Comment by kevin-brown** [comment]
@adopilot The patch mentioned in https://github.com/select2/select2/issues/3354#issuecomment-132389291 still works for 4.0.1 and will likely continue to work in the future until a more complete patch is brought in.

**Comment by sirNemanjapro** [comment]
@kevin-brown The patch mentioned in #3354 (comment) does not fully work with 4.0.1 because in some cases, after removing the tag it converts the tag back to text which then needs to be deleted as well.

**Comment by kohepu** [comment]
+1.  The new behaviour is a nice feature, but it is confusing in some contexts.

**Comment by rogovdm** [comment]
The behaviour is confusing, oh yeah.

It would be nice to have an option to bypass this.

**Comment by guoyunhe** [comment]
+1. Think it is better to have an option to delete the tag completely when user type backspace. Otherwise users might have to type too much times or have to use mouse click when deleting unwanted tags.

**Comment by guoyunhe** [comment]
![spectacle s11487](https://cloud.githubusercontent.com/assets/5836790/15533629/2ef7f39a-226e-11e6-8b0e-3563a5a591bf.png)

When type backspace several times

![spectacle n11487](https://cloud.githubusercontent.com/assets/5836790/15533661/4c4a98e4-226e-11e6-89ba-a0fd78541e5a.png)

**Comment by mephiztophelez** [comment]
+1 have an option to delete tag completely when user presses backspace.

**Comment by nichcz** [comment]
+1 need delete whole tag on backspace press

**Comment by fernicolosi** [comment]
+1

**Comment by Tsuyoshi84** [comment]
+1

**Comment by isaak-zmg** [comment]
my english is not good,there is my method:
    var $eventSelect = $(".roles_selcet2");
    $eventSelect.on("select2:unselect", () => {
            $eventSelect.on("select2:open", () => {
                $(".select2-search__field").val("");
            })
            
        })

hope can be help

**Comment by ghilios** [comment]
I ran into some issues with the callback not being called before other application code pulled in select2 via a require. To ensure this runs synchronously (before the original searchRemoveChoice is cached in a DecoratedMethod), use the following modification

``` javascript
$.fn.select2.amd.require(['select2/selection/search'], function (Search) {
    Search.prototype.searchRemoveChoice = function (decorated, item) {
        this.trigger('unselect', {
            data: item
        });

        this.$search.val('');
        this.handleSearch();
    };
}, null, true);
```

**Comment by xxRockOnxx** [comment]
+1

**Comment by Ecksters** [comment]
+1

**Comment by purell** [comment]
+1 to add the options proposed by @chrisrueger
https://github.com/DVD27/select2/commit/5800beea87dd9ab9dc294a4e0bcc7b5ab825c147

It make more sense
Best regards,

**Comment by pptyasar** [comment]
+1

**Comment by petrlosa** [comment]
+1

**Comment by thejoeejoee** [comment]
+1

**Comment by markoj3s** [comment]
+1

**Comment by recepkutuk** [comment]
I even have a case where I would prefer the tags to be removed only by clicking the "x" icon, so: +1

**Comment by guyisra** [comment]
Are updates on this? this is a severe usability issue, especially on mobile where ever tap counts
Why does this need to wait until for a new release and not fixed? this is a bug, not a feature

**Comment by alexweissman** [comment]
It's not a bug, as described in @kevin-brown's original response.  However it does seem like there are enough people asking for this, that it should be added as a configuration option.  Could also help to address the accessibility issue described in #4105.

**Comment by p4rnicke** [comment]
+1

**Comment by Karmalakas** [comment]
+1

Especially, when I'm using a `templateSelection`. I have to pass my text as `some|text|part` and in selection show only `some`. In this case, pressing Backspace, converts `some` to full editable `some|text|part` string.

**Comment by legshooter** [comment]
@jmlacroix hit the nail on the head.

So a configuration option is very much needed.

And if I had to choose a default, I'd go with completely deleting the tag, because otherwise it doesn't make sense at all in the scenario where the user is choosing from premade options -- but does kinda work the other way around, just makes the user work a bit more, i.e. re-typing.

**Comment by henrynw** [comment]
+1

Please! :)

**Comment by henrynw** [comment]
Got around this by commenting out this line (2123 in 4.0.6-rc.0):
//this.$search.val(item.text);

Context:

  Search.prototype.searchRemoveChoice = function (decorated, item) {
    this.trigger('unselect', {
      data: item
    });

    //this.$search.val(item.text);
    this.handleSearch();
  };

**Comment by pedrofurtado** [comment]
We don't have immediate plans to provide this. We are focused to fix some major UI bugs (that are majority of issues and PR's). But if you open a PR with unit tests, I will be glad to review and approve if everything is ok :+1:

**Comment by Karmalakas** [comment]
Looks like randomly clicking a "Close" button :/

**Comment by stouch** [comment]
That worked for me : 
```
// "this" is a DOM element binded with select2 :
if ($(this).attr('multiple')) {
    $(this).on('select2:unselect', function (event) {
        var $el = $(this)
        setTimeout(function () {
            $('.select2-search__field', $el.closest('.form-row')).focus();
            $el.select2('open');
            $('.select2-search__field', $el.closest('.form-row')).val('');
        }, 0)
    });
    $(this).on('select2:select', function (event) {
        var $el = $(this);
        $el.select2('open');
        setTimeout(function () {
            $('.select2-search__field', $el.closest('.form-row')).focus();
        });
    });
}
```

**Comment by felipebn** [comment]
Another solution:

```
(function($select2Obj){
	$select2Obj
		.parent()
		.find('.select2-selection')
		.on('keydown', '.select2-search--inline', function(evt){
			var backspaceKey = 8;
			if(evt.which == backspaceKey){
				var currentSelection = $select2Obj.select2('data').map(function(s){return s.id});
				$select2Obj.val(currentSelection).trigger("change");
				$select2Obj.select2("close");
			}
		})
})($("#yourSelect2Id"));
```

Also for customization the selection and result, avoid encoding your values using separators like `option text|another useful info that will go in a tooltip` and include them in the JSON you provide as select2 data, easier and does not have issues with the backspace situation.

**Comment by Reforced** [comment]
+1, Please provide a simple option if possible.. e.g. $("#foobar").select2({ clearTermOnBackspace: true })

**Comment by maxcorbeau** [comment]
The way I see things:

- 1 key benefits of select boxes is that users don't have to type it all
- So if users don't have to type it all
- Why make them untype it all?

**Current behaviour means it can be considerably more work to UNDO than to DO which seems a UX anomaly** (it's normally the other way around, you can simply delete, do Ctrl+Z, press cancel/previous etc...).

Example from the official demos https://select2.org/selections#limiting-the-number-of-selections:
 - Selecting California = 2 keystrokes (C+Enter)
 - Unselecting California = 11 keystores (1 initial backspace + 1 for each character)

**Hence why IMO an option to allow removing the entire tag with 1 backspace would be good** (clicking on the X icon forces the use of the mouse which reduces productivity as we need to get hands off the keyboard, click, and back on keyboard again).

**Comment by hiteshsuthar** [comment]
> +1, Please provide a simple option if possible.. e.g. $("#foobar").select2({ clearTermOnBackspace: true })
> Thanks @kevin-brown for [#3354 (comment)](https://github.com/select2/select2/issues/3354#issuecomment-132389291)

Is there any chance of getting this option?

**Comment by maxcorbeau** [comment]
@kevin-brown : any timeline for merging https://github.com/select2/select2/pull/5752 ? Many thanks.

**Comment by BKSpurgeon** [comment]
> ```
> (function($select2Obj){
> 	$select2Obj
> 		.parent()
> 		.find('.select2-selection')
> 		.on('keydown', '.select2-search--inline', function(evt){
> 			var backspaceKey = 8;
> 			if(evt.which == backspaceKey){
> 				var currentSelection = $select2Obj.select2('data').map(function(s){return s.id});
> 				$select2Obj.val(currentSelection).trigger("change");
> 				$select2Obj.select2("close");
> 			}
> 		})
> })($("#yourSelect2Id"));
> ```


Thanks for your answer: would you know how one would integrate the above into their existing select2 javascript code? Here is my existing javascript file:

```javascript
import $ from 'jquery'
import 'select2/dist/css/select2.css'
import 'select2'

window.addEventListener('turbolinks:load', () => {
  var select2 = $('.select2').select2({
  	tags: true,
  	tokenSeparators: [',', ' ', ";"],
  	maximumInputLength: 5000
  });
})
```

**Comment by kevin-brown** [comment]
At this point the behaviour is super broken depending on the options you're using. This will likely be fixed once we figure out the best way to handle deleting choices using the keyboard. That might mean changing the backspace key to instead focus the last option, with a second backspace meaning removing it entirely. Also the backspace key might be unbound for the "clear all" option, since apparently we don't consistently pick one of the other.

**Comment by BKSpurgeon** [comment]
@kevin-brown chrs for the update.

**Comment by kevin-brown** [comment]
One of the tracking WAI ARIA tickets that will allow us to figure out a good pattern for keyboard accessibility is https://github.com/w3c/aria/issues/689. Unfortunately it looks like that ticket has gone silent, so it may need to be kicked up again with some suggestions.

Until then I'm going to hold off on changing this behaviour around significantly. Right now the only way we can be somewhat accessible is by having it behave the way it currently does.

**Comment by vsajip** [comment]
Not sure if a different issue, but when I press backspace I get a completely unrelated option removed from the select. See

https://jsfiddle.net/vsajip/pd642s5m/1/

for a demonstration. Notice how the "red" entry disappears after the first backspace, as well as losing the "black" pill:

![example of odd behavior](https://i.imgur.com/WhOqheI.gif "example of odd behavior")

**Comment by mowali** [comment]
so, all of these comments and still no solution!
OK, anything in the backlog of this library to get this issue fixed?

**Comment by VictorDPuch** [comment]
im using "Select2 4.1.0-beta.1"

Just replace the next line on script 

}), this.$search.val(t.text), this.handleSearch()

for this one 

}), this.$search.val(''), this.handleSearch()

**Comment by georgejoseph1994** [comment]
> > Hey could someone by chance (@kevin-brown) explain if there's a way to override the Search.searchRemoveChoice without forking the repo?
> 
> You can patch this method (not totally recommended but it gets the job done) or create a custom decorator (lacking docs to link to) that overrides this method.
> 
> Here's a jsfiddle that demonstrates the patching method
> 
> https://jsfiddle.net/zmh90ewu/
> 
> And here's the code for it
> 
> ```js
> $.fn.select2.amd.require(['select2/selection/search'], function (Search) {
>     var oldRemoveChoice = Search.prototype.searchRemoveChoice;
> 
>     Search.prototype.searchRemoveChoice = function () {
>         oldRemoveChoice.apply(this, arguments);
>         this.$search.val('');
>     };
> 
>     $('#test').select2({
>         width:'300px'
>     });
> });
> ```

This worked for me thanks

**Comment by Mihai-github** [comment]
Hi, for me the above solution did not work, I used other solution that works for me but... I have a weird behavior when I add values and try to remove one pressing the backspace removes all the values the are already inside the input...

**Comment by alwinkpc** [comment]
> 

Consider using `e.key` attribute as `e.which` is non-standard as stated [here](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/which)

[MDN key reference](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)

**Comment by timmer3** [comment]
this is an old topic but still relevant as the default 'backspace to free text' behaviour is jarring with our users.  a select component has nothing to do with free-text (apart from the useful search feature) so it doesn't make sense to turn a select item into free text.  all this does is force the user delete the characters one by one.  
i looked at the recent commit 77544c0 and it adds an option for multipleOnBackspaceChoice = unselect / none / text 
however the unselect option clears the entire selection, not just the one the user hit backspace on...
would it work to have a fourth option to this setting multipleOnBackspaceChoice like 'single_unselect' or similar?  from the 81 comments on this thread over 9 years i think maybe it's a desirable behaviour :)  would be a great addition to select2 whether as default or as an option.
