### ISSUE TITLE
Error when form name with [] array

### ISSUE THREAD

**Issue by nurmanhabib** [select2/select2#3618]
For example I created a form select using [] array.
```
<select name="kunjungan[temp-0][details][1][details]" class="form-control select2">
    <option value="somevalue">Some Value</option>
    <option value="othervalue">OtherValue</option>
</select>
```
Then I initialization select()
```
$('.select2').select()
```

then when I observed on the web browser console, an error occurs.
```
SyntaxError: invalid range in character class
```
I tried to eliminate the name without the array. The results are normal.
```
<select name="kunjungan_temp-0_details_1_details" class="form-control select2">
    <option value="somevalue">Some Value</option>
    <option value="othervalue">OtherValue</option>
</select>
```

**Comment by kevin-brown** [comment]
Can you expand upon the issue you are facing by adding a few more pieces of information to your bug report?

- What steps can be used to reproduce the issue?
- What is the bug and what is the expected outcome?
- What browser(s) and Operating System have you tested with?
- Does the bug happen consistently across all tested browsers?
- What version of jQuery are you using? And what version of Select2?
- Are you using Select2 with other plugins?

The [contributing guide][cg] contains a useful section with a few questions which can help us track down the bug and speed up the process of finding a fix for it.  The creation of [an isolated test case][test-case] would also be useful.

[cg]: https://github.com/select2/select2/blob/master/CONTRIBUTING.md#reporting-bugs-with-select2
[test-case]: http://css-tricks.com/6263-reduced-test-cases/

**Comment by nurmanhabib** [comment]
Like the example I reported above, the actual plugin select2() is running normally.
```
<select name="kunjungan[temp-0][details][1][details]" class="form-control select2">
```
Bug:
select2 selector can not seem parsing dashes in "temp-0", because I've just tried without dashes `kunjungan[temp0][details][1][details]` running normally

I've tried with Mozilla Firefox 39.0

I also use some plugins, such as TinyMCE, typeahead, and others.

jQuery v2.1.4
Select2 4.0.0

**Comment by Max-Might** [comment]
I get the same error with Select2 4.0.1 and jQuery 2.1.4
The error happens always when selecting a value from a drop-down.

Tested with browsers Firefox 42 and Opera 34.

**Comment by Max-Might** [comment]
> select2 selector can not seem parsing dashes in "temp-0"

Yeah, this seems to be the problem.
IMO this issue is quite critical because it prevents people from using select2.

**Comment by semmais** [comment]
there is also a problem when in the name there is a "-" is followed by a number.

name="group[guid-xp]" - ok
name="group[guid-2]" - error
name="group[id-200]" - error

example: https://jsfiddle.net/ogg1o102/

**Comment by bnjmnhndrsn** [comment]
I ran into this issue in our own code. It actually appears to be the result of a more general bug relating to any time square bracket appears in an attribute `name`.

The problem is that [generateId](https://github.com/select2/select2/blob/master/src/js/select2/core.js#L96) takes the name attribute directly and then uses it for namespacing events, e.g. [here](https://github.com/select2/select2/blob/master/src/js/select2/dropdown/attachBody.js#L87). It looks like jQuery passes the namespace strings directly into a [RegExp constructor] (https://github.com/jquery/jquery/blob/master/src/event.js#L240) when matching events and so the square brackets get treated as regex square brackets. 

This results in the errors above because the namespace is a malformed regex. It also causes other bugs any time a square bracket appears in a name. Because jQuery is interpreting the square brackets as regex square brackets, it can't correctly unbind events attached when there is a square bracket in the event namespace. Look at [this fiddle for example](https://jsfiddle.net/vtojt4wo/1/). In fact, I encountered this bug for that reason. A scroll handler wasn't getting correctly unbound when the select2 container closed.

Because the bug is the result of `_generateId`, a workaround in the short term is adding an `id` attribute to the `select` in question. I'd be happy to submit a pull request, too, to fix the bug in the next few days when I have the time.

**Comment by kevin-brown** [comment]
I think [escaping the name/id](https://learn.jquery.com/using-jquery-core/faq/how-do-i-select-an-element-by-an-id-that-has-characters-used-in-css-notation/) in `_generateId` should fix the issue in all cases. We create all ids for other elements based on the result of `_generateId`, so any issues in elements down the line should also be fixed by escaping selectors there.

**Comment by kingIZZZY** [comment]
Still experiencing this issue
Select2 shows empty placeholder, empty display options, and overall entirely empty select2 control when using brackets in `<select>` element's `name` attribute

```
<select name="something_foo_bar[1][]" data-placeholder="+ Add Something" multiple></select>
```

```
$('select[name^=something_foo_bar]').select2({data: [
    {
        id: 0,
        text: 'enhancement'
    },
    {
        id: 1,
        text: 'bug'
    },
    {
        id: 2,
        text: 'urgent'
    },
    {
        id: 3,
        text: 'valid'
    },
    {
        id: 4,
        text: 'musttfix'
    }
]})
```
