### ISSUE TITLE
mousedown event listener is not detached with destroy()

### ISSUE THREAD

**Issue by alekseybobkov** [select2/select2#3774]
Select2: 4.0.0
jQuery: 2.1.3

After the control is destroyed, it leaves a few detached DOM elements:

![cl7o](https://cloud.githubusercontent.com/assets/481606/9924589/b42ecdb0-5cb5-11e5-8fe9-0415a6a30aef.png)

The element is referred through the context of the mousedown event handler, which is registered in AttachBody.prototype.bind:

```
    this.$dropdownContainer.on('mousedown', function (evt) {
      evt.stopPropagation();
    });
```

That could be solved with adding the select2 namespace to the event name when it's bound and unbinding it in AttachBody.prototype.destroy:

```
    this.$dropdownContainer.on('mousedown.select2', function (evt) {
      evt.stopPropagation();
    });
  };
  ...

 AttachBody.prototype.destroy = function(decorated) {
   this.$dropdownContainer.off('.select2')
   decorated.call(this);
 }
```

Page used for the test:

```
    <script>
        function createSelect2()
        {
           $('#myselect').select2()
        }

        function removeSelect2()
        {
           $('#myselect').select2('destroy')
           $('#myselect').remove()
        }
    </script>

    ...
    <p><select id="myselect"><option value="1">Option 1</option></select></p>

    <input type="button" onclick="createSelect2()" value="Create Select2"/>
    <input type="button" onclick="removeSelect2()" value="Remove Select2"/>
    ...
```

**Comment by kevin-brown** [comment]
This should have been fixed in https://github.com/select2/select2/commit/671f5a2ce21005090e0b69059799cd3dd1fbbf84 and will be included in the upcoming 4.0.1 release.

**Comment by gloventRehan** [comment]
Still not fixed for me. Had to call $('#'+this.idOfSelect2).off();
