### ISSUE TITLE
selected="selected" not working as expected with 4.0.1

### ISSUE THREAD

**Issue by harhoo** [select2/select2#3990]
Have just run into an issue where an upgrade to 4.0.1 has changed functionality over 4.0.0. Not sure if this is expected behaviour. Previously this worked:

```
<select class="dropdown">
<option value="100" selected="selected">Existing Choice</option>
<option value="">No Choice</option>
</select>

<script>
$(function() {
    $(".dropdown").select2({
        data: date_options,
        theme: "bootstrap"
    })
});
</script>
```

where date_options is [{"id":99,"text":"Some Text","type_id":1},{"id":100,"text":"Existing hoice","type_id":5}] etc.

Now, under 4.0.1, the No Choice option is always selected (doesn't matter whether it's first or second in the list).

Downgrading back to 4.0.0 fixes the issue.

**Comment by harhoo** [comment]
Fiddle displaying behaviour: http://jsfiddle.net/harhoo/9k7o9per/

**Comment by kevin-brown** [comment]
At this point, after seeing all of the tickets, this is definitely a bug.

**Comment by champsupertramp** [comment]
I'm also encountering similar issue.

**Comment by lsv** [comment]
+1

**Comment by kevin-brown** [comment]
This should have been fixed by https://github.com/select2/select2/commit/d1ed0a513ab60b41e7a748cec8ffa345544cba27.

**Comment by cknoxrun** [comment]
Hello, this fix seems to just be the failing test -- I am still experiencing the issue in 4.0.6, did I miss something? I am adding an initial option tag with a select that uses ajax. Thank you!

**Comment by andreidiaconescu** [comment]
for me, 
issue reproduces also for setting the data from ajax:
{
  "results": [
    {
      "id": 1,
      "text": "Option 1"
    },
    {
      "id": 2,
      "text": "Option 2",
      "selected": true
    }
  ]
}
the selected option is not shown as selected.

Any idea what i could do ?
Thank you.

**Comment by soniraj** [comment]
A very simple way to tackle this problem is :

//Step1: Here assuming id of your selectbox is my_id, so this will add selected attribute to 1st option $('#my_id option').eq(0).prop('selected',true);

//Step2: Now reinitialize your select box

//This will work, if you haven't initialized selectbox $('#my_id').select2();

or

//This will work, if you have initialized selectbox earlier, so destroy it first and initialise it $('#my_id').select2('destroy').select2();
