### ISSUE TITLE
Bug Scroll search ajax in bootstrap modal

### ISSUE THREAD

**Issue by mahadoang** [select2/select2#4236]
## Steps to reproduce the issue
1. add select2 (search ajax) in bootstrap modal
2. if modal height over window browser  have scroll y
3. click select2 in modal select2 show box for search 
4. then select2 closed the box for search,modal cannot use scroll
## Environment

Browsers
- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

Operating System
- [ ] Mac OS X

Libraries
- jQuery version: 2.1.4
- Select2 version: 4.0.1

**Comment by mahadoang** [comment]
I Fixed By change Line Number : 4142 

$(this).scrollTop(position.y);
TO
$(self).scrollTop(position.y);

**Comment by kalilz4485** [comment]
We had the issue too and used @mahadoang 's fix.

It would be nice if this was merged.

**Comment by kevin-brown** [comment]
This was a duplicate of https://github.com/select2/select2/issues/3125, it should have been fixed in 4.0.2.

**Comment by kalilz4485** [comment]
I still have the issue after updating to 4.0.2.

Can't scroll after changing option in a select (note that in multi selects I can re-scroll if I delete an option, but adding one re-block the scrolling)

**Comment by mahadoang** [comment]
i fixed issue 

Before  fixed

    $watchers.on(scrollEvent, function (ev) {
        var position = $(this).data('select2-scroll-position');
        $(this).scrollTop(position.y);
    });


After fixed
    $watchers.on(scrollEvent, function (ev) {
        var position = $(this).data('select2-scroll-position');
        if($(this).find('.select2-container--open').size()>0)
        {
            $(this).scrollTop(position.y);
        }
    });

working is ok.

**Comment by kalilz4485** [comment]
@mahadoang Have you tried to upgrade to 4.0.2 ? If so did it fix the bug without having you to patch it yourself ?

**Comment by devshangari** [comment]
I tried the same with the upgrade to 4.0.2 and was still having the same issue, the fix by @mahadoang works!

**Comment by luisDanielRoviraContreras** [comment]
buenas amigos el aporte de @mahadoang  esta exelente pero para que funcione en el ultimo jquery en ves de :
`$watchers.on(scrollEvent, function (ev) {
    var position = $(this).data('select2-scroll-position');
    if($(this).find('.select2-container--open').size()>0)
    {
        $(this).scrollTop(position.y);
    }
});`
es 
`$watchers.on(scrollEvent, function (ev) {
    var position = $(this).data('select2-scroll-position');
    if($(this).find('.select2-container--open').length>0)
    {
        $(this).scrollTop(position.y);
    }
});`
hay solo que cambiar el size() por length
saludos es mi primer aporte espero ayude gracias

**Comment by alexweissman** [comment]
I'm reopening this issue because it sounds like some people are still experiencing the problem.

Unfortunately, it really isn't that helpful to just say "it's still not working".  Saying that someone's patch fixed your particular problem is not helpful either, because I have no idea what your code looks like, so I don't know if it's a bug in Select2 or just a problem with the way you're **using** Select2.

**If you want to be really helpful, please try to do the following:**

Create a functioning example in http://jsbin.com or another online JS runner that **fully** demonstrates the problem, with a **minimum** of other unrelated content.

**If you have a patch to Select2 that you believe solves the problem:**

Don't just post it in the issue comments.  This isn't how open source works in 2017.  Clone the repo, implement changes in `src/`, and submit a pull request.  If you don't know how to do this, **learn**.  This is a skill that _every_ software developer needs in today's world.

**Comment by mlawry** [comment]
@alexweissman I think I've managed to pin point the problem (or a variation of the problem) reported by the original poster. It will take some effort for me to explain it so please bear with me.

I've set up a small test case to reproduce this using select2.js 4.0.5: https://select2-in-modal.azurewebsites.net/
Do these steps to reproduce (my variation of) the problem:

- Click on the blue button to launch the bootstrap modal.
- When the modal is shown, adjust your browser window to fit the entire modal so it does **not** scroll.
- Select any number from the select2 drop down options. Wait for a second or so for the modal to refresh.
- Make sure the expanded modal **does** scroll, adjust your window size if necessary but don't make it too small.
- Click on the clear selection cross (x) in the drop down to clear the selection. **Make no further clicks** while waiting a second or so for the modal to refresh. The modal will shrink in size and the drop down options should still be shown.
- After the modal has shrunk, select another number option. Wait a second or so for the modal to refresh and expand again.
- After the modal has expanded, scrolling is not possible using the mouse wheel or arrow keys.

This test page can reproduce the problem in Chrome and Microsoft Edge. The problem is explained by [this comment](https://github.com/select2/select2/issues/3125#issuecomment-245230276) from #3125 

> The problem can be tracked down to this selector:
> `var $watchers = this.$container.parents().filter(Utils.hasScroll)`;
> in both `_attachPositioningHandler()` and `_detachPositioningHandler()` functions.

When `_attachPositioningHandler()` is called `$watchers` included the modal because it was scrolling. But when `_detachPositioningHandler()` is called `$watchers` does not include the modal div because it is no longer scrolling (because we shrank it). As a result, the scrollEvent intercept for the modal div has not been detached and the modal no longer scrolls.

My reproduction of the issue involves the clear selection (x) button and setTimeout() refresh of the modal, but I can imagine a similar case without the clear selection x and setTimeout(), but involves one option resulting in a scrolling modal and another option resulting in a non-scrolling modal. I haven't come up with a test case so I'm not sure if it will indeed be a problem.

As for a fix. I'm thinking perhaps #4942 can do the job because if it stores the elements to which event handlers were bound, then we can be sure `_detachPositioningHandler()` will detach all scroll intercepts attached in `_attachPositioningHandler()`. I will attempt to use the #4942 patch to see if it fixes the problem in my test case.

**Comment by mlawry** [comment]
I tested the following code suggested by @mahadoang

Change
`$(this).scrollTop(position.y);`
TO
`$(self).scrollTop(position.y);`

This will fix the problem, but then if you also comment out the line entirely:

    $watchers.on(scrollEvent, function (ev) {
        var position = $(this).data('select2-scroll-position');
        //$(this).scrollTop(position.y);
    });

It will also fix the problem! The reason is because `$(this).scrollTop(position.y);` is there to prevent the scrolling of the modal div (`this` is the modal div in my test case). Commenting out the line means there is nothing preventing the scrolling of the modal div, hence it scrolls!

However, that line of code shouldn't be called in the first place because scrollEvent should have been detached already in `_detachPositioningHandler()`.

`self` is some decorated element that I don't fully understand but the effect of changing `this` to `self` is the same as commenting out that line.

**Comment by zepernick** [comment]
I have been wrestling with this same issue.  I have 2 select components inside a bootstrap tab, which MAY scroll if it reaches the max height. At random times, the vertical scroll on the tab will lock up after selecting an option inside the select2.  Both of my select's make an ajax call that changes in options in the other select when an option is selected.  

I noticed that I could free up the scroll by clicking inside the select2 that was currently focused and then click off of it.  I have a jsbin that I have been working on, but cannot replicate the problem.  It is intermittent in my application so it is really hard to pin down.  I believe I have a work around without having to modify the select2 source. It attempts to emulate what I was able to manually do to free up the scroll.  I call this after I update the options of the select2 via an ajax call

```js  
$("select.select2")
            .select2("open")
            .select2("close");

$(document.activeElement).blur();
```

**Comment by rizkicahyana** [comment]
Thank you for mentioning this. It really works well when changing `$(this).scrollTop(position.y);` to `$(self).scrollTop(position.y);` 

Thanks @mahadoang and all..

**Comment by sherman89** [comment]
This answer might not be relevant to this problem, but since I managed to get select2 to work perfectly fine in my bootstrap 3 modal, I think it could help someone here.

I was getting strange behavior when I set the `dropdownParent` to the root div of the modal, as the documentation suggests, I had to actually set it to the body of the modal:
`$('#mySelect2').select2({ dropdownParent: $('#myModalContent') });`

Where `#myModalContent` is the element that has `class="modal-content"`.

I answered the same here:
https://github.com/select2/select2-bootstrap-theme/issues/80

Thanks for everyone's contributions!

**Comment by griosa** [comment]
This seems to fix the issue for me as a temporary fix, to try the same actions of _detachPositioningHandler() but with the select2 element actually having parents.

```
$('select').on('select2:select', function() {
      const select2 = $(this).next('.select2');
      const id = $(this).attr('id');

      $.fn.select2.amd.require(['select2/utils'], function (Utils) {
        const $watchers = select2.parents().filter(Utils.hasScroll);
        $watchers.off('scroll.select2.select2-' + id);
      });
});
```

**Comment by rodrigocastro-powerschool** [comment]
This issue is reproducible in **4.0.13** as well. As mentioned in the previous comments changing 
`$(this).scrollTop(position.y); 
`to 
`$(self).scrollTop(position.y); 
`in **select2.full.js@4451** file fixes the problem.

Is there any plan to deploy an official fix of this issue in an upcoming version?

**Comment by catursurapam** [comment]
> I Fixed By change Line Number : 4142
> 
> $(this).scrollTop(position.y); TO $(self).scrollTop(position.y);

hi man, thanks a lot, i struggle this issue too,now its solved, i wonder why the dont make pull request on this bug
