### ISSUE TITLE
select2 Inside of label Not Functioning Correctly

### ISSUE THREAD

**Issue by Gavin-Paolucci-Kleinow** [select2/select2#5137]
A select2 does not work correctly when inside of a label element. In this situation the select2 does not correctly handle text entry.

For example, using this select inside of the a label:
```
<label>
  Select2 Inside Label
  <select>
    <option>a</option>
    <option>b</option>
  </select>
</label>
```

Setting this up as a select2 will create the select2, but when you select the select2 and try to type, the text is not entered into the textbox. I also saw very odd behavior with this situation in my application where typing seemed to open and search inside the select element the select2 replaced.

Here's a working demonstration of this problem:
https://jsfiddle.net/Gavin_Paolucci_Kleinow/pmvbw2z1/2/

**Comment by oh-ren** [comment]
Looks like the textbox loses focus after showing the results.
Only happens when using the mouse to open (click) - there doesn't seem to be a difference when using the keyboard.

When clicking fast enough (close-open) the typing does work.

**Comment by alexweissman** [comment]
Could you please update your fiddle to use the latest release?   A number of issues have been addressed in 4.0.6-rc.0, so it would be helpful to see if this problem is present in the _latest_ version.

**Comment by alexweissman** [comment]
It looks like this issue came up before (of course, there is no such thing as a new issue in Select2 anymore) in #4203.  [This commit](https://github.com/select2/select2/commit/31e7a1d4c52ed7477769fcad5d15166ae3c9b4d0) fixed it in 4.0.3 (see http://jsbin.com/beceqovaxi/edit?html,js,output), but it would appear that a regression was introduced in 4.0.4 (possibly when the fix in #4427 was added).

So, someone needs to look into this and figure out how to fix this to satisfy both issues.

**Comment by nino-s** [comment]
@alexweissman should we open a new pull request or go with the old one? https://github.com/select2/select2/pull/4427. Select2 has a method to check, if the whole container is focused. So lets use this one?

```js
    container.on('focus', function () {
      if (!container.hasFocus()) {
        self.$search.focus();
      }
    });
```

**Comment by alexweissman** [comment]
Let's open a new pull request, since this will be part of a new milestone :-)

**Comment by Gavin-Paolucci-Kleinow** [comment]
@alexweissman You no longer need me to update my fiddle, right?

**Comment by nino-s** [comment]
@alexweissman Pullrequest created - I hope this one does the trick without introducing new issues :/ Sorry for the last one

**Comment by alexweissman** [comment]
@Gavin-Paolucci-Kleinow correct, looks like we got it sorted out.

@nino-s no problem, appreciate your contributions.  We should add some additional tests though, to ensure that we don't end up with further regressions related to element focus later on 😄

**Comment by Gavin-Paolucci-Kleinow** [comment]
Has this issue now been resolved?

**Comment by glen-84** [comment]
@Gavin-Paolucci-Kleinow No.

**Comment by kevin-brown** [comment]
Pulling this from the 4.0.8 milestone because this is a known issue with Select2 being focused but not opened, and it is not unique to Select2 within a `<label>`. Select2 does not detect keypresses on the main element, because there are a ton of accessibility issues with it, so right now it only detects keypresses for searching when the dropdown is opened and the search box is in focus.

This will get fixed eventually. And I may merge this ticket with another one which better reflects the actual issue.

**Comment by kevin-brown** [comment]
After re-reading the original description, it's very likely that this issue was fixed in 4.0.6 (non-RC) or 4.0.7, when we fixed an issue that sounds very similar.

**Comment by kevin-brown** [comment]
There's still an issue with single selects where if you open them while they are within a `<label>`, the focus is moved away from the search box. This appears to be because the focus is moved to the original `<select>`, which may be because of how we try to maintain focus when the search box is revealed.

**Comment by glen-84** [comment]
@kevin-brown,

Could you please reopen this issue?

It's still not working correctly in 4.0.13: https://jsfiddle.net/ox4v295j/

**Comment by DaleyKD** [comment]
Currently using 4.0.13 and clicking the label does nothing.  I have mine set with <label for="{id}">, and obviously that ID is set on the hidden <select>.

**Comment by gardelin** [comment]
This can be temporary solution, until bug is fixed
https://codepen.io/balancana/pen/BaoBMqJ

**Comment by a-p-f** [comment]
Just came here to say that I've also run into this issue, and I had a very hard time narrowing down the cause (my site has a number of select2 fields, with varying options, and a lot of other focus-management code). I ended up reproducing the jsfiddle from the issue description almost exactly before I did an issue search and found this issue.

Do you collect donations or issue bounties for this project? I might be able to convince my employer to send a donation or issue bounty your way.
