### ISSUE TITLE
Data attribute like data-placeholder & other not working after an upgrade to 4.0.6-rc.1 from 4.0.5

### ISSUE THREAD

**Issue by india081947** [select2/select2#5320]
Hello,

After the upgrade from 4.0.5 to 4.0.6-rc.1 data attributes like data-placeholder, minimum-input-length etc not working.

[As per 4.0.5 JSBin](http://jsbin.com/rijowixeha/1/edit?html,js,output) 
[As per  4.0.6-rc.1 JSBin](http://jsbin.com/hijuzetede/2/edit?html,js,output)

As far as I have checked it seem it is due to change in cache of data property using  [Utils.GetData](https://github.com/select2/select2/commit/62c4f6332bb90c9d6013e97a0a97ec6bcd0a83df#diff-d119a26bbb794be11c185e398ebe578e) 

P.S. Creating issue for the first time in this repository, Please Pardon me if I have missed anything special to mention here.

**Comment by Deimoks** [comment]
Can confirm this bug. 

I made some debugs and it seems that keys in **Utils.__cache** are being stored AFTER they are needed, so it always returns _undefined_ when **Utils.GetData** is looking for keys. I checked that these keys are needed in select2/options but they are created (Utils.StoreData) in select2/core, which runs afterwards.

If you need a workaround so that you get data-* attributes to Select2 options, you can do this:

```
$('.select2').each(function() {
    var placeholder = $(this).data('placeholder') || 'Default placeholder';
    $(this).select2({
        placeholder:placeholder,
    }); 
});
```

Just do this with other data-* attributes if you need it, until the issue is solved.

**Comment by india081947** [comment]
Thanks @Deimoks & @pedrofurtado

**Comment by joaopedroraldi** [comment]
> Can confirm this bug.
> 
> I made some debugs and it seems that keys in **Utils.__cache** are being stored AFTER they are needed, so it always returns _undefined_ when **Utils.GetData** is looking for keys. I checked that these keys are needed in select2/options but they are created (Utils.StoreData) in select2/core, which runs afterwards.
> 
> If you need a workaround so that you get data-* attributes to Select2 options, you can do this:
> 
> ```
> $('.select2').each(function() {
>     var placeholder = $(this).data('placeholder') || 'Default placeholder';
>     $(this).select2({
>         placeholder:placeholder,
>     }); 
> });
> ```
> Just do this with other data-* attributes if you need it, until the issue is solved.

It works, but the templates and matcher messes around :cry:

**Comment by przemek-pl** [comment]
Workaround from @joaopedroraldi didn't work for me but I solved it this way:

```
$("#select_field").prepend('<option></option>'); // Empty field for placeholder if not present yet
$("#select_field").attr("data-placeholder", "Placeholder");
$("#select_field").select2({ width: '100%' });
```

**Comment by daveyholler** [comment]
Just wanted to `+1` this issue. I'm attempting a workaround too, but specifically for `data-allow-clear`

```
$('[data-allow-clear]').each(function() {
    $(this).select2({
        allowClear: true
    })
})
```

The clear button displays as expected, but on click the ID returns `null`.

**Comment by eqnet** [comment]
If allowClear: true and NOT placeholder: ""/placeholder: "Some Placeholder" is defined you get and error when clicking on the clear button.

**Comment by nphilipp** [comment]
As I see it, the issue still exists. Bump.

**Comment by crabnky** [comment]
Bump.

**Comment by jonahgreenthal** [comment]
4.0.6-rc1 is just broken and shouldn't be used. Someone was briefly "maintaining" the project and made that release, but actually they just messed tons of stuff up.

**Comment by NadeemAfana** [comment]
All this would have been fixed with the new changes in https://github.com/select2/select2/pull/4346 more than a year ago, but no action was taken.

**Comment by Dannymx** [comment]
Is there a version where this works? I'm using 4.0.6-rc.1 and is still broken.

**Comment by kevin-brown** [comment]
I've been trying to reproduce this ever since the bug was first submitted (admittedly with some large gaps, as many of you have noticed), and I finally figured out why this wasn't caught by the test suite.

The test suite runs against jQuery 1.x, which happens to be the only version of jQuery that does not have this issue. Modifying the test suite to run against jQuery 2.x verifies that this issue does exist.

**Comment by NadeemAfana** [comment]
@kevin-brown,
I had mentioned that fact before. Also, the PR  #4346 I submitted already runs the test suite against both versions of jQuery just in case the issue came back in the future.
