### ISSUE TITLE
I can not add new items to a Select2 list with Tagging support using IE 11

### ISSUE THREAD

**Issue by JacoFourie** [select2/select2#5378]
Hi all.

We use the Oracle Apex Plugin Version of this component. All works fine accept on IE we are not able to add new items to a list by typing and then hitting enter. I know you don't support the plugin here. I did also log the issue on the plug-in page. But I am hoping that somebody could point me to a fix as the plug-in is based on this code.

Here is a sample app. If you use Internet Explorer you will see you are not able to enter new text in the combo box. In any other browser it works 100%

https://apex.oracle.com/pls/apex/f?p=96087:2

Kind Regards.

Jaco.

**Comment by Rocky-bg** [comment]
Hi all,

Could you please help me with some tip how to fix this issue because we use select2 a lot in our project and this IE issue is hard to understand what is going wrong. You can reproduce it on select2 example page : [](https://select2.org/tagging) with Internet Explorer 11.

Best Regards,
Rosen

**Comment by JacoFourie** [comment]
@vandernorth did you fix the issue ? Sorry I have not been on here for some time.

**Comment by JacoFourie** [comment]
Hi. I can confirm that this fixed the issue on IE. Thanks so much for that.

**Comment by jbosse** [comment]
I can confirm this was either not actually resolved or a regression has occurred. You cannot add a tag in IE11. Tested with 4.0.10 min.js

**Comment by jianbinwen** [comment]
This issue still exists in select2 4.0.12. Wonder why this issue was closed.

**Comment by vandernorth** [comment]
Issue still exists when using IE11 and jquery v3.4.1 and select2 v4.0.13. 
Made a new PR #5821 
@kevin-brown any thoughts on this?

**Comment by kevin-brown** [comment]
I was doing some testing of this issue and this appears to have been fixed as a side-effect of the changes made in https://github.com/select2/select2/pull/5842.

**Comment by JacoFourie** [comment]
Hi. I can confirm that the error is still there on IE with version 4.0.13.
We tried to use the beta but that does funny things with text placement.

**Comment by kevin-brown** [comment]
> We tried to use the beta but that does funny things with text placement.

Please open up a ticket if you are finding issues in 4.1.0-beta.1. Noting that custom themes may not yet have been updated to support the new version, so it is possible that the issues you are seeing may be related to theme bugs.

**Comment by JacoFourie** [comment]
Thanks Kevin I will do so. Will you be fixing the IE bug in version 4.0.13 ?
